POST http://localhost:10279/api/v1/warnify/send/dooray
Content-Type: application/json
Accept: application/json

{
  "companyDomain": "javame.com",
  "warnInfo": "두레이발신!!"
}

###
POST http://localhost:10279/api/v1/warnify/send/email
Content-Type: application/json
Accept: application/json

{
  "companyDomain": "javame.com",
  "warnInfo": "이메일ddddddddddddd발신!!"
}

###
POST http://localhost:10281/warnify/sms
Content-Type: application/json
Accept: application/json

{
  "companyDomain": "javame.com",
  "warnInfo": "sms발신!!"
}