POST http://localhost:10281/warnify/dooray
Content-Type: application/json
Accept: application/json

{
  "companyDomain": "zz",
  "warnInfo": "Zz"
}

###

POST http://localhost:10281/api/v1/warnify/sms
Content-Type: application/json
Accept: application/json