POST http://localhost:10281/api/v1/warnify/email
Content-Type: application/json
Accept: application/json

###

POST http://localhost:10281/api/v1/warnify/sms
Content-Type: application/json
Accept: application/json